/**
 * Display names for the alekfull-nx ES-DE theme's system ids (client/public/theme/systems/*).
 * Not every id in the theme pack is a real "system" a user would configure a ROM
 * folder for — a handful are ES-DE meta-categories (settings, tools, emulators,
 * now-playing, completed) or duplicates of a system under another id. Those are
 * excluded from SELECTABLE_SYSTEM_IDS but keep working via getSystemDisplayName
 * if ever referenced (e.g. the fixed source ids: steam/epic/desktop/custom-collections).
 */
const DISPLAY_NAMES: Record<string, string> = {
  "3do": "3DO",
  adam: "Coleco Adam",
  ags: "Adventure Game Studio",
  amiga: "Amiga",
  amiga1200: "Amiga 1200",
  amiga600: "Amiga 600",
  amigacd32: "Amiga CD32",
  amstradcpc: "Amstrad CPC",
  android: "Android",
  androidapps: "Android Apps",
  androidgames: "Android Games",
  apple2: "Apple II",
  apple2gs: "Apple IIGS",
  arcade: "Arcade",
  arcadia: "Arcadia 2001",
  archimedes: "Acorn Archimedes",
  arduboy: "Arduboy",
  astrocade: "Bally Astrocade",
  atari2600: "Atari 2600",
  atari5200: "Atari 5200",
  atari7800: "Atari 7800",
  atari800: "Atari 800",
  atarijaguar: "Atari Jaguar",
  atarijaguarcd: "Atari Jaguar CD",
  atarilynx: "Atari Lynx",
  atarist: "Atari ST",
  atarixe: "Atari XE",
  atomiswave: "Atomiswave",
  "auto-allgames": "All Games",
  "auto-favorites": "Favorites",
  "auto-lastplayed": "Last Played",
  bbcmicro: "BBC Micro",
  c64: "Commodore 64",
  cdimono1: "CD-i",
  cdtv: "Commodore CDTV",
  chailove: "ChaiLove",
  channelf: "Fairchild Channel F",
  coco: "TRS-80 Color Computer",
  colecovision: "ColecoVision",
  cps: "CPS",
  cps1: "CPS-1",
  cps2: "CPS-2",
  cps3: "CPS-3",
  crvision: "VTech CreatiVision",
  "custom-collections": "Custom Apps",
  daphne: "Daphne (LaserDisc)",
  desktop: "Full Desktop",
  doom: "Doom",
  dos: "DOS",
  dragon32: "Dragon 32",
  dreamcast: "Dreamcast",
  easyrpg: "EasyRPG",
  electron: "Acorn Electron",
  epic: "Epic Games",
  famicom: "Famicom",
  fba: "FinalBurn Alpha",
  fbneo: "FinalBurn Neo",
  fds: "Famicom Disk System",
  flash: "Adobe Flash",
  fm7: "Fujitsu FM-7",
  fmtowns: "FM Towns",
  fpinball: "Future Pinball",
  gamate: "Gamate",
  gameandwatch: "Game & Watch",
  gamecom: "Tiger Game.com",
  gamegear: "Game Gear",
  gb: "Game Boy",
  gba: "Game Boy Advance",
  gbc: "Game Boy Color",
  gc: "GameCube",
  genesis: "Genesis",
  gmaster: "Game Master",
  gx4000: "Amstrad GX4000",
  intellivision: "Intellivision",
  j2me: "J2ME",
  kodi: "Kodi",
  lcdgames: "LCD Games",
  lowresnx: "LowRes NX",
  lutro: "Lutro",
  macintosh: "Macintosh",
  mame: "MAME",
  mastersystem: "Master System",
  megacd: "Mega CD",
  megacdjp: "Mega CD (JP)",
  megadrive: "Mega Drive",
  megadrivejp: "Mega Drive (JP)",
  megaduck: "Mega Duck",
  mess: "MESS",
  model2: "Sega Model 2",
  model3: "Sega Model 3",
  msx: "MSX",
  msx1: "MSX1",
  msx2: "MSX2",
  msxturbor: "MSX Turbo R",
  mugen: "M.U.G.E.N",
  multivision: "Multivision",
  n3ds: "Nintendo 3DS",
  n64: "Nintendo 64",
  n64dd: "Nintendo 64DD",
  naomi: "Naomi",
  naomi2: "Naomi 2",
  naomigd: "Naomi GD",
  nds: "Nintendo DS",
  neogeo: "Neo Geo",
  neogeocd: "Neo Geo CD",
  neogeocdjp: "Neo Geo CD (JP)",
  nes: "NES",
  ngage: "N-Gage",
  ngp: "Neo Geo Pocket",
  ngpc: "Neo Geo Pocket Color",
  odyssey2: "Odyssey 2",
  openbor: "OpenBOR",
  oric: "Oric",
  palm: "Palm OS",
  pc: "PC",
  pc88: "PC-88",
  pc98: "PC-98",
  pcarcade: "PC Arcade",
  pcengine: "PC Engine",
  pcenginecd: "PC Engine CD",
  pcfx: "PC-FX",
  pico8: "PICO-8",
  playdate: "Playdate",
  plus4: "Commodore Plus/4",
  pokemini: "Pokémon Mini",
  ports: "Ports",
  ps2: "PlayStation 2",
  ps3: "PlayStation 3",
  ps4: "PlayStation 4",
  psp: "PSP",
  psvita: "PS Vita",
  psx: "PlayStation",
  pv1000: "Casio PV-1000",
  quake: "Quake",
  samcoupe: "SAM Coupé",
  satellaview: "Satellaview",
  saturn: "Saturn",
  saturnjp: "Saturn (JP)",
  scummvm: "ScummVM",
  scv: "Super Cassette Vision",
  sega32x: "Sega 32X",
  sega32xjp: "Sega 32X (JP)",
  sega32xna: "Sega 32X (NA)",
  segacd: "Sega CD",
  sfc: "Super Famicom",
  "sg-1000": "SG-1000",
  sgb: "Super Game Boy",
  snes: "SNES",
  snesna: "SNES (NA)",
  solarus: "Solarus",
  spectravideo: "Spectravideo",
  steam: "Steam",
  stv: "Sega ST-V",
  sufami: "Sufami Turbo",
  supergrafx: "SuperGrafx",
  supervision: "Watara Supervision",
  supracan: "Super A'Can",
  switch: "Nintendo Switch",
  symbian: "Symbian",
  tanodragon: "Tano Dragon",
  "tg-cd": "TurboGrafx-CD",
  tg16: "TurboGrafx-16",
  ti99: "TI-99/4A",
  tic80: "TIC-80",
  to8: "Thomson TO8",
  "trs-80": "TRS-80",
  triforce: "Triforce",
  "type-x": "Type X",
  uzebox: "Uzebox",
  vectrex: "Vectrex",
  vic20: "VIC-20",
  videopac: "Videopac",
  virtualboy: "Virtual Boy",
  vpinball: "Visual Pinball",
  vsmile: "V.Smile",
  wii: "Wii",
  wiiu: "Wii U",
  windows: "Windows",
  wonderswan: "WonderSwan",
  wonderswancolor: "WonderSwan Color",
  x1: "Sharp X1",
  x68000: "Sharp X68000",
  xbox: "Xbox",
  xbox360: "Xbox 360",
  zx81: "ZX81",
  zxspectrum: "ZX Spectrum",
};

/** Ids excluded from the ROM-folder "console" picker: ES-DE meta-categories,
 * not real systems, or already covered by a fixed app source. */
const NON_SELECTABLE_IDS = new Set([
  "_default",
  "completed",
  "consolearcade",
  "custom-collections",
  "desktop",
  "emulators",
  "epic",
  "steam",
  "settings",
  "tools",
  "now-playing",
  "auto-allgames",
  "auto-favorites",
  "auto-lastplayed",
  "ibm",
  "moto",
  "mark3",
  "mame-advmame",
  "mame-libretro",
]);

export function getSystemDisplayName(id: string): string {
  return (
    DISPLAY_NAMES[id] ??
    id
      .split(/[-_]/)
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join(" ")
  );
}

export const SELECTABLE_SYSTEM_IDS = Object.keys(DISPLAY_NAMES)
  .filter((id) => !NON_SELECTABLE_IDS.has(id))
  .sort((a, b) => getSystemDisplayName(a).localeCompare(getSystemDisplayName(b)));
